### PR TITLE
dropdown component bugfixes

### LINKED ISSUE #268: Bug report: CopyItem shows success state for multiple copied items simultaneously
## IS: Current behavior
When a dropdown has multiple `CopyItem`s, both items can appear copied at once:

https://user-images.githubusercontent.com/903288/166738940-8c215c3a-18de-42df-87d7-c0a6d61591d8.mov

## SHOULD BE: Expected behavior
Only one CopyItem should appear copied at a time.

## Steps to reproduce
1. Navigate to https://design-system-components-hashicorp.vercel.app/components/dropdown
2. Find the section for "ToggleButton + Title, Description, CopyItem, Separator"
3. Click to expand and open the example dropdown
4. Click to copy one item, and then the other
5. Notice you see the green copy icon (aka success state) for both 

## Possible solution
The dropdown should optionally be able to keep track of whether one of its child `CopyItem`s has been copied & clear the copied item when a new one is selected.

### PR DESCRIPTION
**Pull request by MelSumner**
### :pushpin: Summary

If merged, this PR: 

1. updates the `copy-item` to use async/await. While we are using the [native web api for clipboard](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText), it was suggested that `async`/`await` is preferable to `.then` because it is more readable.
2. adds a `setTimeout` for the "success" state to fade back to the default after copying the item (would this sufficiently resolve #268 ?)
3. updates the documentation to include the copy-item API 
4. updates a mismatched/incorrect example with the invocation shown on the page

Remaining question(s):

1. Testing the copy-item action. While we have guards in place (comparing the result of `readText` with `this.args.text`), I've tried a few different approaches to write an accurate test for the action but it doesn't seem like I can get the clipboard action to accurately test - `promise rejected...document not focused`.  
2. The WCAG conformance of using `setTimeout` to change the state from success back to default after being copied.

### :camera_flash: Screenshots

Added the copy-item API: 
CleanShot 2022-05-05 at 16 39 34

Updated the code sample to match what was implemented:
CleanShot 2022-05-05 at 16 34 25

### 👀 How to review

👉 Review by files changed

Reviewer's checklist:

- [ ] +1 Percy if applicable
- [ ] Confirm that PR has a changelog update via [Changesets](https://github.com/changesets/changesets) if needed

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1202167094155069

### CODE REVIEW

File: packages/components/addon/components/hds/dropdown/list-item/copy-item.js [hunk 1]
```diff
@@ -4,7 +4,7 @@ import { tracked } from '@glimmer/tracking';
 import { action } from '@ember/object';
 
 export default class HdsDropdownListItemCopyItemComponent extends Component {
-  @tracked isSuccess = this.args.isSuccess ?? false;
+  @tracked isSuccess = false;
```
Comment (didoo) [inline packages/components/addon/components/hds/dropdown/list-item/copy-item.js:7]: [nitpick/not blocker] maybe we could leave it `undefined` by default, so we can use the `false` state for when there is an error.

File: packages/components/addon/components/hds/dropdown/list-item/copy-item.js [hunk 2]
```diff
@@ -37,12 +37,19 @@ export default class HdsDropdownListItemCopyItemComponent extends Component {
...
+    await navigator.clipboard.writeText(this.args.text);
+    const result = await navigator.clipboard.readText();
+
+    if (result === this.args.text) {
       this.isSuccess = true;
+      // console.log(`result is ${result}`);
+
+      // make it fade back to the default state
+      setTimeout(() => {
+        this.isSuccess = false;
```
Comment (didoo) [inline packages/components/addon/components/hds/dropdown/list-item/copy-item.js:51]: [nitpick/not blocker] see comment above about `false` vs `undefined`

File: packages/components/addon/components/hds/dropdown/list-item/copy-item.js [hunk 3]
```diff
@@ -37,12 +37,19 @@ export default class HdsDropdownListItemCopyItemComponent extends Component {
...
+  async copyCode() {
+    // https://developer.mozilla.org/en-US/docs/Web/API/Clipboard
+    await navigator.clipboard.writeText(this.args.text);
+    const result = await navigator.clipboard.readText();
+
+    if (result === this.args.text) {
       this.isSuccess = true;
+      // console.log(`result is ${result}`);
+
+      // make it fade back to the default state
```
Comment (didoo) [inline packages/components/addon/components/hds/dropdown/list-item/copy-item.js:49]: 👍👍👍

File: packages/components/addon/components/hds/dropdown/list-item/copy-item.js [hunk 4]
```diff
@@ -37,12 +37,19 @@ export default class HdsDropdownListItemCopyItemComponent extends Component {
...
-    navigator.clipboard.writeText(this.args.text);
-    // this if statement resolves to [object Promise] so maybe some improvements
-    // could be made here
-    if (navigator.clipboard.readText()) {
+  async copyCode() {
+    // https://developer.mozilla.org/en-US/docs/Web/API/Clipboard
+    await navigator.clipboard.writeText(this.args.text);
+    const result = await navigator.clipboard.readText();
+
+    if (result === this.args.text) {
```
Comment (didoo) [inline packages/components/addon/components/hds/dropdown/list-item/copy-item.js:45]: [nitpick/improvement] since we have a "getter" function for the value `this.text`, and potentially thiw function could be manipulating the value in the future, it would be more resilient if here we use `this.text` (and at line 41 too) instead of the argument passed.

**Review by didoo — APPROVED** [review]
👍

File: packages/components/addon/components/hds/dropdown/list-item/copy-item.js (hunk 2 above)
Comment (MelSumner) [reply packages/components/addon/components/hds/dropdown/list-item/copy-item.js:51]: https://github.com/hashicorp/design-system/issues/275

File: packages/components/addon/components/hds/dropdown/list-item/copy-item.js (hunk 4 above)
Comment (MelSumner) [reply packages/components/addon/components/hds/dropdown/list-item/copy-item.js:45]: there's a reason to use this.args.text but I need to look it up. I'll find the text so we can all have the same knowledge and will update this PR if I am not correct.

**Comment by Dhaulagiri** [comment]
Definitely open to ideas on how to best remember this, but in order for this bugfix to be "released" this PR should have included a changset

**Comment by didoo** [comment]
> Definitely open to ideas on how to best remember this, but in order for this bugfix to be "released" this PR should have included a changeset

My bad, again 🤦‍♂️
